### ISSUE TITLE
GoReSym package

### ISSUE THREAD

**Issue by HanEmile** [radareorg/radare2-pm#160]
## Description

*Please describe what are you missing or wanting to be improved*

A package for [hanemile/radare2-GoReSym](https://github.com/hanemile/radare2-GoReSym), as [suggested by pancake](https://infosec.exchange/@pancake/112287103980983834).

Essentially this would allow installing the package and thus installing [mandiant/GoReSym](https://github.com/mandiant/GoReSym). One could then use `mandiant/GoReSym` inline in order to extract the symbols from the current binary from within radare2 and then import those symbols using `hanemile/radare2-GoReSym`.

*Provide images, ascii-art, test files and anything that may help us understand your request*

Well, I've got no images, but I've copied another package as I've got no idea how this is actually done:

```
R2PM_BEGIN

R2PM_DESC "import symbols from GoReSym"

R2PM_INSTALL() {
	git clone https://github.com/mandiant/GoReSym
	pushd GoReSym
	go build
	popd

        git clone https://github.com/hanemile/radare2-GoReSym
	
	# Extract the symbols from the binary like this
	# GoReSym -t -d -p BINARY > goresym_out.txt
	#
	# Then within radare2:
	# [0x........]> . radare2GoReSym/rename.py
	#
	# Wait a bit and finally, the sumbols are renamed accordingly
}

R2PM_UNINSTALL() {
        rm -rf GoReSym radare2-GoReSym
}

R2PM_END
```

**Comment by trufae** [comment]
Ideally you shouldnt be git cloning from the install block. and this package wont work unless you add a R2PM_GIT or TGZ directive. I may probably write an r2pm linter and a manpage to make those things clearer :) So my suggestions are:

* Create two packages and use R2PM_DEPS to make one pkg depend on the other.
* Use R2PM_GIT with the url of the repository on each pkg
* Copy the rename.py script into the R2PM_BINDIR, so it can be launched directly from r2
* I would suggest to create an r2pipe script (available from the R2PM_BINDIR) that have options to extract the symbols from the binary (run the line in your comment) or rename the symbols by running the line below.
* This script can be named "r2goresym" and can be executed with `#!pipe r2goresym` if you do this script in r2js you can just register a new command inside r2 and do everything in javascript, which is probably cleaner and easier to use because you have access to all the paths and such.
